### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by 75lb** [jsdoc2md/jsdoc-to-markdown#4]
These are my notes.

- [ ] bugs
  - [x] constructor desc missing but classdesc description showing on ES6 class (cla)
  - [ ] `@param [options.newLine=os.EOL]` puts the default in quotes, which it shouldn't 
  - [ ] `--example-lang off` not mentioned in usage
  - [ ] documenting a quoted property includes the quotes (`"\"bg-red\""`), it doesn't need them
  - [ ] this [issue](https://github.com/jesucarr/tokenbucket/pull/2)
  - [ ] @typedef doesn't show a type, it should be `myType : typedef`
  - [ ] module anchor tag has disappeared, e.g. `array-tools#module_array-tools` - `{{#module}}` should always output anchor
  - [ ] a custom tag which is a flag (e.g. `@non-standard`) does not require a colon.. 
  - [ ] should @interface names show in italics, like @abstract
  - [ ] `@fulfil {{ name: string }[]} - a recordset of room objects` doesn't look right.. (see muc)
  - [ ] use `something` if `module:something` doesn't resolve?
  - [ ] do example grouped by kind
  - [ ] markdown in param desc [looks broke](https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/options/formatting%20options)
  - [ ] `{@link module:fifo~Task}` linking to the constructor, not the class
  - [ ] set sort order of modules in the main-index and docs
  - [ ] jsdoc-parse, if a class is @private is there any point returning the child members?
  - [ ] --include-inherited option, for easier life where there's a class extended from a diff module
  - [ ] should `sgr.sequence` header be `ansi.sgr.sequence`
  - [ ] @properties should appear in the namespace member list
  - [ ] jsdoc-parse should throw stuff like 'ERROR: The @memberof tag requires a value.' as an error, not write it to stderr
  - [ ] `@param [val=1] {number}` reports a defaultvalue of `"1"`, string instead of number
  - [ ] if `@module` has no docs, use the description from the exported value (e.g the classdesc)
- [ ] tags
  - [ ] `@order` tag to override the computed
  - [ ] @requires
  - [ ] reflect `nullable` types
  - [ ] extra field ("component" or something) on all members of identifier including the parent for use in sorting
- [ ] options / overrides
  - [ ] --class-member-index should have table option, showing the description alongside the API (array-tools)
  - [ ] 'index-depth' option - set the max depth for main and member index
  - [x] configure symbols (exported, returns etc)
- [ ] what to do about `"memberof": "<anonymous>"`.. create an artificial anon identifier to act as the parent? 
- [ ] document 
  - [ ] markdown is rendered in no-gfm param tables, only
  - [ ] directly exporting a function should be avoided due to this bug: https://github.com/jsdoc3/jsdoc/issues/679
  - [ ] leave @default without a value to pickup the correct type
  - [ ] @see rule on external without desc
- [ ] custom templates
  - [ ] possible to have separate index page plus one page per identifier, or hand-picked group of identifiers
- [ ] an easier way to export a class than `@alias module:cjs/deep`? something like `@export`? 
- [x] should dmd be more lenient, not depending on correct hierarchy? 
- [ ] larger tasks
  - [x] factor markdown-tables out into sep project
  - [ ] write dmd input data format spec, to enable other parsers to use dmd
  - [ ] internationalisation
  - [ ] dmd sandpit
  - [x] refactor dmd partials by structure and content, tags and sections etc.. 
  - [ ] break up into many smaller apps.. using handlebars to build a README is a suggestion, not a dep.. shove multiple commands output into readme, e.g. `module-index` into `{{module-index}}`, `git shortlog -sn` into `{{shortlog}}`

**Comment by jmealo** [comment]
@75lb is possible to add #49 to this with your other @see work
